import type { Metadata } from "next";

// import "bootstrap/scss/bootstrap.scss";
import "@/assets/scss/app.scss";
import AppWrappersProvider from "@/components/AppWrappersProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWrappersProvider>{children}</AppWrappersProvider>
      </body>
    </html>
  );
}
